spring:
  application:
    name: komtekProject

  datasource:
    url: jdbc:postgresql://localhost:5432/komtek_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jackson:
    default-property-inclusion: non_null

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: medical
  jpa:
    properties:
      hibernate:
          efault_schema: medical
logging:
    level:
      com.example.komtekProject: DEBUG
      com.example.komtekProject.aspect: DEBUG
      org.springframework: WARN
      org.hibernate: WARN
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file:
      name: logs/komtek-app.log
      max-size: 10MB
      max-history: 30

