spring:
  application:
    name: komtekProject

  datasource:
    url: jdbc:postgresql://localhost:5432/komtek_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

  jackson:
    default-property-inclusion: non_null

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: medical
  jpa:
    properties:
      hibernate:
          default_schema: medical

logging:
  charset:
    console: UTF-8
  level:
      com.example.komtekProject: DEBUG
      com.example.komtekProject.aspect: DEBUG
      org.springframework: WARN
      org.hibernate: WARN
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
      name: logs/komtek-app.log
      max-size: 10MB
      max-history: 30

