spring:
  application:
    name: komtekProject

  datasource:
    url: jdbc:postgresql://localhost:5432/komtek_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
jackson:
  default-property-inclusion: non_null
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
